

services:
  # MySQL
  mysql:
    image: mysql:latest
    container_name: mysql-demo
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynet




volumes:
  mysql_data:

networks:
  mynet:
    driver: bridge